---
- name: Prepare Cilium CLI on first master and deploy CNI
  when: inventory_hostname == groups[server_group][0] or ansible_host == groups[server_group][0]
  run_once: true
  block:
    - name: Create tmp directory on first master
      ansible.builtin.file:
        path: /tmp/k3s
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Check if Cilium CLI is installed
      ansible.builtin.command: cilium version
      register: cilium_cli_installed
      failed_when: false
      changed_when: false
      ignore_errors: true

    - name: Check for Cilium CLI version in command output
      ansible.builtin.set_fact:
        installed_cli_version: >-
          {{
            cilium_cli_installed.stdout_lines
            | join(' ')
            | regex_findall('cilium-cli: (v\d+\.\d+\.\d+)')
            | first
            | default('unknown')
          }}
      when: cilium_cli_installed.rc == 0

    - name: Get latest stable Cilium CLI version file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
        dest: /tmp/k3s/cilium-cli-stable.txt
        owner: root
        group: root
        mode: "0755"

    - name: Read Cilium CLI stable version from file
      ansible.builtin.command: cat /tmp/k3s/cilium-cli-stable.txt
      register: cli_ver
      changed_when: false

    - name: Log installed Cilium CLI version
      ansible.builtin.debug:
        msg: "Installed Cilium CLI version: {{ installed_cli_version | default('Not installed') }}"

    - name: Log latest stable Cilium CLI version
      ansible.builtin.debug:
        msg: "Latest Cilium CLI version: {{ cli_ver.stdout }}"

    - name: Determine if Cilium CLI needs installation or update
      ansible.builtin.set_fact:
        cilium_cli_needs_update: >-
          {{
            cilium_cli_installed.rc != 0 or
            (cilium_cli_installed.rc == 0 and
            installed_cli_version != cli_ver.stdout)
          }}

    - name: Install or update Cilium CLI
      when: cilium_cli_needs_update
      block:
        - name: Set architecture variable
          ansible.builtin.set_fact:
            cli_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

        - name: Download Cilium CLI and checksum
          ansible.builtin.get_url:
            url: "{{ cilium_base_url }}/cilium-linux-{{ cli_arch }}{{ item }}"
            dest: /tmp/k3s/cilium-linux-{{ cli_arch }}{{ item }}
            owner: root
            group: root
            mode: "0755"
          loop:
            - .tar.gz
            - .tar.gz.sha256sum
          vars:
            cilium_base_url: https://github.com/cilium/cilium-cli/releases/download/{{ cli_ver.stdout }}

        - name: Verify the downloaded tarball
          ansible.builtin.shell: |
            cd /tmp/k3s && sha256sum --check cilium-linux-{{ cli_arch }}.tar.gz.sha256sum
          args:
            executable: /bin/bash
          changed_when: false

        - name: Extract Cilium CLI to /usr/local/bin
          ansible.builtin.unarchive:
            src: /tmp/k3s/cilium-linux-{{ cli_arch }}.tar.gz
            dest: /usr/local/bin
            remote_src: true

        - name: Remove downloaded tarball and checksum file
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - /tmp/k3s/cilium-linux-{{ cli_arch }}.tar.gz
            - /tmp/k3s/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum

    - name: Wait for Kubernetes API endpoint
      ansible.builtin.wait_for:
        host: "{{ api_endpoint }}"
        port: 6443
        timeout: 60
        delay: 1
      register: api_test_result
      ignore_errors: true
      changed_when: false

    - name: Fail if kubernetes API endpoint not reachable
      ansible.builtin.fail:
        msg: API endpoint {{ api_endpoint }} is not reachable
      when: api_test_result is failed

    - name: Check if Cilium is already installed
      ansible.builtin.command: >-
        helm list -n {{ cilium_namespace | default('kube-system')}} --filter {{ cilium_repo_name }}
      register: cilium_installed
      failed_when: false
      changed_when: false
      ignore_errors: false

    - name: Add Cilium Helm repo
      kubernetes.core.helm_repository:
        name: "{{ cilium_repo_name }}"
        repo_url: "https://helm.cilium.io"
        state: present

    - name: Get latest Cilium chart info from Helm repo
      ansible.builtin.command: >
        helm show chart {{ cilium_repo_name }}/{{ cilium_chart_name }}
      register: helm_chart_info
      changed_when: false

    - name: Parse chart version from Helm output
      ansible.builtin.set_fact:
        cilium_latest_version: "{{ (helm_chart_info.stdout | from_yaml).version }}"

    - name: Get installed Cilium version
      ansible.builtin.set_fact:
        installed_cilium_version: >-
          {{
            cilium_installed.stdout_lines[1].split()[8].split('-')[-1]
            if cilium_installed.rc == 0 and cilium_installed.stdout_lines | length > 1
            else 'none'
          }}
      when: cilium_installed.rc == 0 and cilium_installed.stdout_lines | length > 1

    - name: Log Cilium installation status
      ansible.builtin.debug:
        msg: >
          Installed Cilium version: {{ installed_cilium_version | default('Not installed') }},
          Target Cilium version: {{ cilium_version | default(cilium_latest_version) }}

    - name: Determine if Cilium needs installation or upgrade
      ansible.builtin.set_fact:
        cilium_needs_install: >-
          {{
            cilium_installed.rc != 0 or
            cilium_installed.stdout_lines | length <= 1 or
            installed_cilium_version != cilium_version | default(cilium_latest_version)
          }}

    - name: Create Cilium values file
      ansible.builtin.template:
        src: templates/chartvalues.j2
        dest: /tmp/k3s/cilium-values.yaml
        owner: root
        group: root
        mode: "0644"
      
    - name: Install or upgrade Cilium using Helm
      kubernetes.core.helm:
        name: "{{ cilium_release_name }}"
        chart_ref: "{{ cilium_repo_name }}/{{ cilium_chart_name }}"
        release_namespace: "{{ cilium_namespace | default('kube-system')}}"
        chart_version: "{{ cilium_version | default(cilium_latest_version) }}"
        create_namespace: true
        values_files:
          - /tmp/k3s/cilium-values.yaml
        state: present
        atomic: true
        wait: true
        timeout: "600s"
        force: false
      register: cilium_helm_result
      when: cilium_needs_install

    - name: Wait for Cilium pods to be ready
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: kube-system
        label_selectors:
          - k8s-app=cilium
        wait: true
        wait_condition:
          type: Ready
          status: "True"
        wait_timeout: 30

    - name: Wait for Cilium operator to be ready
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: cilium-operator
        namespace: kube-system
        wait: true
        wait_condition:
          type: Available
          status: "True"
        wait_timeout: 30

    - name: Wait for Hubble components (if enabled)
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: "{{ item }}"
        namespace: kube-system
        wait: true
        wait_condition:
          type: Available
          status: "True"
        wait_timeout: 300
      loop:
        - hubble-relay
        - hubble-ui
      when: cilium_hubble | default(false)

    - name: Create CiliumLoadBalancerIPPool yaml file
      ansible.builtin.template:
        src: templates/cilium.crs.j2
        dest: /tmp/k3s/cilium-values.yaml
        owner: root
        group: root
        mode: "0644"

    - name: Set context for Cilium CLI
      ansible.builtin.command: cilium context --helm-release-name {{ cilium_release_name }} --helm-namespace {{ cilium_namespace | default('kube-system') }}
      failed_when: false
      changed_when: false

    - name: Apply Cilium BGP configuration
      when: cilium_bgp | default(false)
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'cilium.crs.j2') | from_yaml }}"

    - name: Verify BGP configuration
      kubernetes.core.k8s_info:
        api_version: cilium.io/v2alpha1
        kind: CiliumLoadBalancerIPPool
      when: cilium_bgp | default(false)
