cilium_release_name: cilium
cilium_repo_name: cilium
cilium_chart_name: cilium
cilium_version: 1.18.1


cilium_bgp: false
cilium_bgp_advertise_svc: false
cilium_bgp_local_asn: 65000
cilium_bgp_peer_asn: 65001
cilium_bgp_lb_cidr: 192.168.31.0/24


cilium_hubble: true
cilium_mode: native # native when nodes on same subnet or using bgp, else set routed
cilium_hubble_service_type: ClusterIP


cluster_cidr: 10.42.0.0/16
enable_bpf_masquerade: false
kube_proxy_replacement: false
api_endpoint: 127.0.0.1
api_port: 6443
server_group: server  # noqa var-naming[no-role-prefix]