cilium_bgp: false
cilium_exportPodCIDR: true  # noqa var-naming
cilium_bgp_lb_cidr: 192.168.31.0/24
cilium_hubble: true
cilium_mode: native

cluster_cidr: 10.42.0.0/16
enable_bpf_masquerade: true
kube_proxy_replacement: true
server_group: server  # noqa var-naming[no-role-prefix]