cilium_release_name: cilium
cilium_repo_name: cilium
cilium_chart_name: cilium
cilium_version: 1.18.1

cilium_l2: false
cilium_l2_interface: eth0
cilium_exportPodCIDR: false
cilium_lb_cidr: 192.168.31.0/24
cilium_hubble: true
cilium_mode: native
cilium_hubble_service_type: NodePort
cilium_hubble_ui_nodeport: 30090


cluster_cidr: 10.42.0.0/16
enable_bpf_masquerade: false
kube_proxy_replacement: false
api_endpoint: 127.0.0.1
api_port: 6443
server_group: server  # noqa var-naming[no-role-prefix]