---
# cluster_cidr: "{{ (server_config_yaml | from_yaml)['cluster-cidr'] | default('10.42.0.0/16') }}"  # noqa var-naming[no-role-prefix]
# service_cidr: "{{ (server_config_yaml | from_yaml)['service-cidr'] | default('10.43.0.0/16') }}"  # noqa var-naming[no-role-prefix]
cluster_cidr: "10.42.0.0/16"  # noqa var-naming[no-role-prefix]
service_cidr: "10.43.0.0/16"  # noqa var-naming[no-role-prefix]