---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: airgap
    # - role: raspberrypi

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - role: k3s_server
  environment: "{{ kubeconfig_env }}"

# - name: Setup K3S agent
#   hosts: agent
#   become: true
#   roles:
#     - role: k3s_agent


- name: Install/Upgrade Cilium on K3S server
  hosts: server
  become: true
  roles:
    - role: cilium
      when: install_cilium | default(false)
  environment: "{{ kubeconfig_env }}"
  tags: 
    - cilium

- name: Install/Upgrade Cert-Manager on K3S server
  hosts: server
  become: true
  roles:
    - role: certmanager
      when: install_certmanager | default(false)
  environment: "{{ kubeconfig_env }}"
  tags: 
    - certmanager

- name: Install/Upgrade Argocd on K3S server
  hosts: server
  become: true
  roles:
    - role: argocd
      when: install_argocd | default(false)
  environment: "{{ kubeconfig_env }}"
  tags: 
    - argocd
  