---
name: Build
on:
  push:
    branches:
      - master

jobs:

  test:
    name: Build Ansible Galaxy collection artifact.
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: pip3 install ansible

      - name: Build artifact.
        run: ansible-galaxy collection build

      - name: Upload artifact.
        uses: actions/upload-artifact@v4
        with:
          name: galaxy-collection
          path: k3s-orchestration-*.tar.gz
